spring:
  application:
    name: stock-viewer-app

server:
  port: 8080

logging:
  level:
    com.example.stockviewer: INFO
    org.springframework.web: INFO

brapi:
  base-url: https://brapi.dev
  token: bvNapWwLQzGouyRNT2WvXm


#bvNapWwLQzGouyRNT2WvXm